# -*- coding: utf-8 -*-
"""bark_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJfA2XUa-mXwdMy7DoYKVYHI1iTd9Vkt

## Install
"""

# install bark (make sure you have torch>=2 for much faster flash-attention)
!pip install git+https://github.com/suno-ai/bark.git

"""## Basics"""

from bark import SAMPLE_RATE, generate_audio, preload_models
from IPython.display import Audio

preload_models()

text_prompt = """
     Hello, my name is Suno. And, uh — and I like pizza. [laughs]
     But I also have other interests such as playing tic tac toe.
"""
audio_array = generate_audio(text_prompt)
Audio(audio_array, rate=SAMPLE_RATE)

"""## Advanced examples"""

text_prompt = """
    Buenos días Miguel. Tu colega piensa que tu alemán es extremadamente malo.
    But I suppose your english isn't terrible.
"""
audio_array = generate_audio(text_prompt)
Audio(audio_array, rate=SAMPLE_RATE)

text_prompt = """
    WOMAN: I would like an oatmilk latte please.
    MAN: Wow, that's expensive!
"""
audio_array = generate_audio(text_prompt)
Audio(audio_array, rate=SAMPLE_RATE)

text_prompt = """
    I have a silky smooth voice, and today I will tell you
    about the exercise regimen of the common sloth.
"""
audio_array = generate_audio(text_prompt, history_prompt="v2/en_speaker_1")
Audio(audio_array, rate=SAMPLE_RATE)



